/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    preview?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Карточки проектов, которые выводятся в портфолио.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * Латиница, дефисы и цифры. Используется для CSS-класса карточки.
   */
  slug: string;
  category: 'business' | 'services' | 'lifestyle' | 'concept';
  /**
   * Например: e-commerce / catalog
   */
  kind: string;
  /**
   * Разделяйте теги символом ·
   */
  tags?: string | null;
  /**
   * Изображение карточки. Можно заменить в любой момент.
   */
  cover?: (number | null) | Media;
  /**
   * Необязательно. Например: project-cover--aura
   */
  coverClassName?: string | null;
  /**
   * Используется до загрузки CMS-обложки или для миграции старых карточек.
   */
  fallbackCover?: string | null;
  visualMode: 'image' | 'orb';
  orbLabel?: string | null;
  overlayLineOne?: string | null;
  overlayLineTwo?: string | null;
  alt?: string | null;
  /**
   * Ссылка на поддомен проекта, например https://project.example.ru. На время миграции допустим локальный путь.
   */
  previewUrl: string;
  /**
   * Меньшее число — выше в портфолио.
   */
  sortOrder: number;
  cardVariant: 'default' | 'wide';
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        preview?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  category?: T;
  kind?: T;
  tags?: T;
  cover?: T;
  coverClassName?: T;
  fallbackCover?: T;
  visualMode?: T;
  orbLabel?: T;
  overlayLineOne?: T;
  overlayLineTwo?: T;
  alt?: T;
  previewUrl?: T;
  sortOrder?: T;
  cardVariant?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  site: {
    title: string;
    description: string;
    brandName: string;
    brandTagline: string;
    brandAriaLabel: string;
    navProjects: string;
    navServices: string;
    navProcess: string;
    navContact: string;
    headerCta: string;
    location: string;
    telegramLabel: string;
    emailLabel: string;
    backToTopLabel: string;
    telegramUrl?: string | null;
    emailUrl?: string | null;
  };
  hero: {
    year: string;
    status: string;
    eyebrow: string;
    titleLineOne: string;
    titleEmphasis: string;
    titleLineTwo: string;
    titleDot: string;
    lead: string;
    primaryCta: string;
    secondaryCta: string;
    portrait?: (number | null) | Media;
    portraitFallback?: string | null;
    portraitAlt: string;
    portraitCaptionLabel: string;
    portraitCaptionLineOne: string;
    portraitCaptionLineTwo: string;
    badgeOne: string;
    badgeTwo: string;
    badgeThree: string;
    coordinate: string;
    index: string;
    scrollLabel: string;
    metrics?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  marquee?: {
    items?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  portfolio: {
    sectionLabel: string;
    headingLineOne: string;
    headingEmphasis: string;
    sideCopy: string;
    liveLabel: string;
    emptyText: string;
    projectsCountSuffix: string;
    directionsCountSuffix: string;
    approachLabel: string;
    footerLink: string;
  };
  filters: {
    all: string;
    business: string;
    services: string;
    lifestyle: string;
    concept: string;
  };
  services: {
    sectionLabel: string;
    headingLineOne: string;
    headingEmphasis: string;
    lead: string;
    tags?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    items?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    note: string;
  };
  process: {
    sectionLabel: string;
    headingLineOne: string;
    headingEmphasis: string;
    lead: string;
    photo?: (number | null) | Media;
    photoFallback?: string | null;
    photoAlt: string;
    stampLineOne: string;
    stampEmphasis: string;
    stampLineTwo: string;
    photoIndex: string;
    kicker: string;
    titleLineOne: string;
    titleEmphasis: string;
    copy: string;
    steps?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  contact: {
    sectionLabel: string;
    headingLineOne: string;
    headingLineTwo: string;
    headingEmphasis: string;
    lead: string;
    responseLabel: string;
    nameLabel: string;
    namePlaceholder: string;
    contactLabel: string;
    contactPlaceholder: string;
    typeLabel: string;
    typeOptions?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    messageLabel: string;
    messagePlaceholder: string;
    submitLabel: string;
    statusText: string;
  };
  preview: {
    defaultKind: string;
    defaultTitle: string;
    defaultTags: string;
    loaderText: string;
    browserLabel: string;
    frameTitle: string;
    externalLabel: string;
    hint: string;
    closeLabel: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  site?:
    | T
    | {
        title?: T;
        description?: T;
        brandName?: T;
        brandTagline?: T;
        brandAriaLabel?: T;
        navProjects?: T;
        navServices?: T;
        navProcess?: T;
        navContact?: T;
        headerCta?: T;
        location?: T;
        telegramLabel?: T;
        emailLabel?: T;
        backToTopLabel?: T;
        telegramUrl?: T;
        emailUrl?: T;
      };
  hero?:
    | T
    | {
        year?: T;
        status?: T;
        eyebrow?: T;
        titleLineOne?: T;
        titleEmphasis?: T;
        titleLineTwo?: T;
        titleDot?: T;
        lead?: T;
        primaryCta?: T;
        secondaryCta?: T;
        portrait?: T;
        portraitFallback?: T;
        portraitAlt?: T;
        portraitCaptionLabel?: T;
        portraitCaptionLineOne?: T;
        portraitCaptionLineTwo?: T;
        badgeOne?: T;
        badgeTwo?: T;
        badgeThree?: T;
        coordinate?: T;
        index?: T;
        scrollLabel?: T;
        metrics?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  marquee?:
    | T
    | {
        items?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  portfolio?:
    | T
    | {
        sectionLabel?: T;
        headingLineOne?: T;
        headingEmphasis?: T;
        sideCopy?: T;
        liveLabel?: T;
        emptyText?: T;
        projectsCountSuffix?: T;
        directionsCountSuffix?: T;
        approachLabel?: T;
        footerLink?: T;
      };
  filters?:
    | T
    | {
        all?: T;
        business?: T;
        services?: T;
        lifestyle?: T;
        concept?: T;
      };
  services?:
    | T
    | {
        sectionLabel?: T;
        headingLineOne?: T;
        headingEmphasis?: T;
        lead?: T;
        tags?:
          | T
          | {
              label?: T;
              id?: T;
            };
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        note?: T;
      };
  process?:
    | T
    | {
        sectionLabel?: T;
        headingLineOne?: T;
        headingEmphasis?: T;
        lead?: T;
        photo?: T;
        photoFallback?: T;
        photoAlt?: T;
        stampLineOne?: T;
        stampEmphasis?: T;
        stampLineTwo?: T;
        photoIndex?: T;
        kicker?: T;
        titleLineOne?: T;
        titleEmphasis?: T;
        copy?: T;
        steps?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        sectionLabel?: T;
        headingLineOne?: T;
        headingLineTwo?: T;
        headingEmphasis?: T;
        lead?: T;
        responseLabel?: T;
        nameLabel?: T;
        namePlaceholder?: T;
        contactLabel?: T;
        contactPlaceholder?: T;
        typeLabel?: T;
        typeOptions?:
          | T
          | {
              label?: T;
              id?: T;
            };
        messageLabel?: T;
        messagePlaceholder?: T;
        submitLabel?: T;
        statusText?: T;
      };
  preview?:
    | T
    | {
        defaultKind?: T;
        defaultTitle?: T;
        defaultTags?: T;
        loaderText?: T;
        browserLabel?: T;
        frameTitle?: T;
        externalLabel?: T;
        hint?: T;
        closeLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}