import type { Access, GlobalConfig } from 'payload'

const isAuthenticated: Access = ({ req }) => Boolean(req.user)

const text = (name: string, label: string, required = true) => ({
  name,
  type: 'text' as const,
  label,
  required,
})

const textarea = (name: string, label: string, required = true) => ({
  name,
  type: 'textarea' as const,
  label,
  required,
})

export const SiteSettings: GlobalConfig = {
  slug: 'site-settings',
  label: 'Контент главной',
  access: {
    read: () => true,
    update: isAuthenticated,
  },
  fields: [
    {
      name: 'site',
      type: 'group',
      label: 'Сайт и бренд',
      fields: [
        text('title', 'Заголовок вкладки'),
        textarea('description', 'Meta description'),
        text('brandName', 'Название бренда'),
        text('brandTagline', 'Подпись бренда'),
        text('brandAriaLabel', 'Aria-label бренда'),
        text('navProjects', 'Навигация — проекты'),
        text('navServices', 'Навигация — услуги'),
        text('navProcess', 'Навигация — подход'),
        text('navContact', 'Навигация — контакты'),
        text('headerCta', 'Кнопка в шапке'),
        text('location', 'Локация и формат работы'),
        text('telegramLabel', 'Подпись ссылки Telegram'),
        text('emailLabel', 'Подпись ссылки Email'),
        text('backToTopLabel', 'Подпись ссылки наверх'),
        text('telegramUrl', 'Ссылка Telegram', false),
        text('emailUrl', 'Ссылка Email', false),
      ],
    },
    {
      name: 'hero',
      type: 'group',
      label: 'Hero',
      fields: [
        text('year', 'Подпись года'),
        text('status', 'Статус доступности'),
        text('eyebrow', 'Надзаголовок'),
        text('titleLineOne', 'Заголовок — строка 1'),
        text('titleEmphasis', 'Заголовок — акцентная строка'),
        text('titleLineTwo', 'Заголовок — строка 3'),
        text('titleDot', 'Знак после заголовка'),
        textarea('lead', 'Описание под заголовком'),
        text('primaryCta', 'Основная кнопка'),
        text('secondaryCta', 'Вторичная ссылка'),
        {
          name: 'portrait',
          type: 'upload' as const,
          relationTo: 'media' as const,
          label: 'Портрет в hero',
        },
        text('portraitFallback', 'Резервный путь портрета', false),
        text('portraitAlt', 'Alt портрета'),
        text('portraitCaptionLabel', 'Подпись портрета — label'),
        text('portraitCaptionLineOne', 'Подпись портрета — строка 1'),
        text('portraitCaptionLineTwo', 'Подпись портрета — строка 2'),
        text('badgeOne', 'Badge — слово 1'),
        text('badgeTwo', 'Badge — слово 2'),
        text('badgeThree', 'Badge — слово 3'),
        text('coordinate', 'Координаты'),
        text('index', 'Индекс'),
        text('scrollLabel', 'Подпись scroll'),
        {
          name: 'metrics',
          type: 'array' as const,
          label: 'Метрики hero',
          minRows: 1,
          maxRows: 3,
          fields: [text('value', 'Значение'), textarea('label', 'Подпись')],
        },
      ],
    },
    {
      name: 'marquee',
      type: 'group',
      label: 'Бегущая строка',
      fields: [
        {
          name: 'items',
          type: 'array' as const,
          label: 'Направления',
          minRows: 1,
          fields: [text('label', 'Текст направления')],
        },
      ],
    },
    {
      name: 'portfolio',
      type: 'group',
      label: 'Портфолио',
      fields: [
        text('sectionLabel', 'Номер и название секции'),
        text('headingLineOne', 'Заголовок — строка 1'),
        text('headingEmphasis', 'Заголовок — акцент'),
        textarea('sideCopy', 'Описание секции'),
        text('liveLabel', 'Метка live previews'),
        text('emptyText', 'Пустое состояние фильтра'),
        text('projectsCountSuffix', 'Подпись количества проектов'),
        text('directionsCountSuffix', 'Подпись количества направлений'),
        text('approachLabel', 'Подпись подхода'),
        text('footerLink', 'Ссылка под проектами'),
      ],
    },
    {
      name: 'filters',
      type: 'group',
      label: 'Фильтры проектов',
      fields: [
        text('all', 'Все'),
        text('business', 'Бизнес'),
        text('services', 'Сервисы'),
        text('lifestyle', 'Lifestyle'),
        text('concept', 'Эксперименты'),
      ],
    },
    {
      name: 'services',
      type: 'group',
      label: 'Услуги',
      fields: [
        text('sectionLabel', 'Номер и название секции'),
        text('headingLineOne', 'Заголовок — строка 1'),
        text('headingEmphasis', 'Заголовок — акцент'),
        textarea('lead', 'Описание секции'),
        {
          name: 'tags',
          type: 'array' as const,
          label: 'Теги услуг',
          fields: [text('label', 'Тег')],
        },
        {
          name: 'items',
          type: 'array' as const,
          label: 'Услуги',
          minRows: 1,
          fields: [text('title', 'Название'), textarea('description', 'Описание')],
        },
        text('note', 'Подпись под услугами'),
      ],
    },
    {
      name: 'process',
      type: 'group',
      label: 'Подход',
      fields: [
        text('sectionLabel', 'Номер и название секции'),
        text('headingLineOne', 'Заголовок — строка 1'),
        text('headingEmphasis', 'Заголовок — акцент'),
        textarea('lead', 'Описание секции'),
        {
          name: 'photo',
          type: 'upload' as const,
          relationTo: 'media' as const,
          label: 'Фотография секции',
        },
        text('photoFallback', 'Резервный путь фотографии', false),
        text('photoAlt', 'Alt фотографии'),
        text('stampLineOne', 'Штамп — строка 1'),
        text('stampEmphasis', 'Штамп — акцент'),
        text('stampLineTwo', 'Штамп — строка 3'),
        text('photoIndex', 'Индекс фотографии'),
        text('kicker', 'Надзаголовок текста'),
        text('titleLineOne', 'Заголовок текста — строка 1'),
        text('titleEmphasis', 'Заголовок текста — акцент'),
        textarea('copy', 'Основной текст'),
        {
          name: 'steps',
          type: 'array' as const,
          label: 'Этапы',
          minRows: 1,
          fields: [text('title', 'Название'), text('description', 'Описание')],
        },
      ],
    },
    {
      name: 'contact',
      type: 'group',
      label: 'Контакты',
      fields: [
        text('sectionLabel', 'Номер и название секции'),
        text('headingLineOne', 'Заголовок — строка 1'),
        text('headingLineTwo', 'Заголовок — строка 2'),
        text('headingEmphasis', 'Заголовок — акцент'),
        textarea('lead', 'Описание'),
        text('responseLabel', 'Срок ответа'),
        text('nameLabel', 'Поле имени'),
        text('namePlaceholder', 'Placeholder имени'),
        text('contactLabel', 'Поле контакта'),
        text('contactPlaceholder', 'Placeholder контакта'),
        text('typeLabel', 'Поле типа задачи'),
        {
          name: 'typeOptions',
          type: 'array' as const,
          label: 'Варианты задачи',
          minRows: 1,
          fields: [text('label', 'Вариант')],
        },
        text('messageLabel', 'Поле описания'),
        text('messagePlaceholder', 'Placeholder описания'),
        text('submitLabel', 'Кнопка формы'),
        text('statusText', 'Сообщение после отправки'),
      ],
    },
    {
      name: 'preview',
      type: 'group',
      label: 'Предпросмотр проектов',
      fields: [
        text('defaultKind', 'Тип по умолчанию'),
        text('defaultTitle', 'Заголовок по умолчанию'),
        text('defaultTags', 'Теги по умолчанию'),
        text('loaderText', 'Текст загрузки'),
        text('browserLabel', 'Подпись адресной строки'),
        text('frameTitle', 'Заголовок iframe'),
        text('externalLabel', 'Ссылка на отдельное открытие'),
        text('hint', 'Подсказка под предпросмотром'),
        text('closeLabel', 'Aria-label закрытия'),
      ],
    },
  ],
}
